user: 
  - name: canonical
  - home: /home/canonical
  - uid: 2000
  - gid: 2000
  - groups:
    - sudoers
    - qwerty
  - group_name: sudoers 
  - group_gid: 2000 
  - user_to_del: canonic1al
  - ssh_public_key: salt://tests/users/ubuntu.pem.pub
  - ssh_private_key:  salt://tests/users/ubuntu.pem
